### ISSUE TITLE
Docs/examples of basic functionality

### ISSUE THREAD

**Issue by 5anchezzz** [radianceteam/ton-client-ruby#16]
Hi! Please show examples of how to use this gem to perform such functionality:

1. Creating an address
2. Transferring tokens from this address to another.

Unfortunately, I can't find any documentation on this issue.
Thanks!

**Comment by 5anchezzz** [comment]
Is it correct structure of a KeysPar? I mean second "secret" value...

**Comment by GildedHonour** [comment]
Noted

> Is it correct structure of a KeyPair? I mean second "secret" value...
Yes. Why not?

**Comment by GildedHonour** [comment]
This will be moved over to Wiki, if needed
