### ISSUE TITLE
Doesnt work with libriary

### ISSUE THREAD

**Issue by user090909** [radianceteam/ton-client-ruby#29]
I use this bin https://github.com/tonlabs/TON-SDK/releases/tag/1.22.0 linux
And copy it in /home/user/.local/share/gem/ruby/3.0.0/gems/ton_sdk_client-1.22.0/tonclient.so
i have x64 and its not trouble with my pc.

/home/user/.local/share/gem/ruby/3.0.0/gems/ffi-1.15.3/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library '/home/user/.local/share/gem/ruby/3.0.0/gems/ton_sdk_client-1.22.0/tonclient.so': /home/user/.local/share/gem/ruby/3.0.0/gems/ton_sdk_client-1.22.0/tonclient.so: invalid ELF header (LoadError)
	from /home/user/.local/share/gem/ruby/3.0.0/gems/ffi-1.15.3/lib/ffi/library.rb:99:in `map'
	from /home/user/.local/share/gem/ruby/3.0.0/gems/ffi-1.15.3/lib/ffi/library.rb:99:in `ffi_lib'
	from /home/user/.local/share/gem/ruby/3.0.0/gems/ton_sdk_client-1.22.0/lib/ton_sdk_client/interop.rb:55:in `<module:Interop>'
	from /home/user/.local/share/gem/ruby/3.0.0/gems/ton_sdk_client-1.22.0/lib/ton_sdk_client/interop.rb:7:in `<module:TonSdk>'
	from /home/user/.local/share/gem/ruby/3.0.0/gems/ton_sdk_client-1.22.0/lib/ton_sdk_client/interop.rb:6:in `<top (required)>'
	from /home/user/.local/share/gem/ruby/3.0.0/gems/ton_sdk_client-1.22.0/lib/ton_sdk_client/client_context.rb:3:in `require_relative'
	from /home/user/.local/share/gem/ruby/3.0.0/gems/ton_sdk_client-1.22.0/lib/ton_sdk_client/client_context.rb:3:in `<top (required)>'
	from /home/user/.local/share/gem/ruby/3.0.0/gems/ton_sdk_client-1.22.0/lib/ton_sdk_client.rb:2:in `require_relative'
	from /home/user/.local/share/gem/ruby/3.0.0/gems/ton_sdk_client-1.22.0/lib/ton_sdk_client.rb:2:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
	from main.rb:2:in `<main>'
<internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- ton_sdk_client (LoadError)
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from main.rb:2:in `<main>'

**Comment by user090909** [comment]
This one https://binaries.tonlabs.io/tonclient_1_linux.gz 
Check pls why

**Comment by Paprikas** [comment]
Tonclient 0 is not supported anymore by Tonlabs, Use 1 major version
